services:
  # Base de datos para Odoo (Mantenida local porque Odoo la requiere)
  db:
    image: postgres:15
    container_name: crm-db-1
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    networks:
      - crm-network
    restart: unless-stopped

  # El sistema Odoo CRM
  odoo:
    image: odoo:17.0
    container_name: crm-odoo-1
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./odoo_data:/var/lib/odoo
      - ./odoo_addons:/mnt/extra-addons
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    networks:
      - crm-network
    restart: unless-stopped

  # --- BACKEND DJANGO (CONECTADO AL DATA WAREHOUSE EN SOMEE) ---
  django:
    build: .
    container_name: django_app
    env_file:
      - .env
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - crm-network
    restart: unless-stopped

  # --- FRONTEND REACT ---
  frontend:
    image: node:20-alpine
    container_name: react_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    ports:
      - "3000:3000"
    command: sh -c "npm install && HOST=0.0.0.0 npm start"
    environment:
      - WDS_SOCKET_PORT=0
      - WATCHPACK_POLLING=true
    stdin_open: true
    tty: true
    networks:
      - crm-network
    restart: unless-stopped

networks:
  crm-network:
    driver: bridge