version: '3.1'

services:
  # Base de datos para Odoo
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    networks:
      - crm-network

  # El sistema Odoo
  odoo:
    image: odoo:17.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./odoo_data:/var/lib/odoo
      - ./odoo_addons:/mnt/extra-addons
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    networks:
      - crm-network

  # SQL Server para la base de Samsung
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=160305Encinas+
    ports:
      - "1433:1433"
    networks:
      - crm-network

  # --- NUEVO SERVICIO: DJANGO ---
  django:
    build: .
    container_name: django_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - SQL_SERVER_HOST=sqlserver
      - SQL_SERVER_USER=sa
      - SQL_SERVER_PASSWORD=160305Encinas+
      - ODOO_DB_HOST=db
    depends_on:
      - sqlserver
      - db
    networks:
      - crm-network
  frontend:
    image: node:20-alpine
    container_name: react_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    ports:
      - "3000:3000"
    command: sh -c "npm install && HOST=0.0.0.0 npm start"
    environment:
      - WDS_SOCKET_PORT=0
      - WATCHPACK_POLLING=true
    stdin_open: true
    tty: true
    networks:
      - crm-network

networks:
  crm-network:
    driver: bridge